// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WF_Sem2CA1.Models;

#nullable disable

namespace WF_Sem2CA1.Migrations
{
    [DbContext(typeof(StudyContext))]
    partial class StudyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("WF_Sem2CA1.Models.Department", b =>
                {
                    b.Property<string>("DeptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("WF_Sem2CA1.Models.Module", b =>
                {
                    b.Property<string>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentDeptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ModuleId");

                    b.HasIndex("DepartmentDeptId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("WF_Sem2CA1.Models.StudyHelp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("ModuleId");

                    b.ToTable("StudyHelp");
                });

            modelBuilder.Entity("WF_Sem2CA1.Models.Module", b =>
                {
                    b.HasOne("WF_Sem2CA1.Models.Department", "Department")
                        .WithMany("Modules")
                        .HasForeignKey("DepartmentDeptId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WF_Sem2CA1.Models.StudyHelp", b =>
                {
                    b.HasOne("WF_Sem2CA1.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("WF_Sem2CA1.Models.Department", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
